### ISSUE TITLE
Command Execution bug 

### ISSUE THREAD

**Issue by EarlyGamer45** [Infinite-Plugins/Infinite-Vouchers#1]
[Wiki]: https://docs.infiniteplugins.com

_Use this template as a guideline for reporting Infinite Plugins related issues. Please use pastebin or another text service for reporting stacktraces._

Make sure you have previously:
- [X] Read the [Wiki] for any information.
- [X] Checked that you've installed all dependencies of the plugin. 
- [X] Checked you're running the latest version of the plugin.
- [X] Checked the issue is not with a third party plugin. (commonly placeholder expansions)

**Issue:**

hi, i found an issue while setting up infinite vouchers if i add 2 commands with the [op] on  the commands doesn't properly work...  and if i remove [op] from 1 command only and on the other i keep it only 1 command work (on the first there's kit vip %name% on the second one kit starter (a usually user command).
**Expected Behaviour:**

**Observed Behaviour:**

**Server Software and Version:**

PaperSpigot 1.8.8
**Other Information:**

**Issue Screenshots or Evidence:**
https://youtu.be/vduzFRT8-T4 - Testing it.
https://pastebin.com/PhVYA1Be - Vouchers.yml

**Comment by CaptainYannick** [comment]
Hey @EarlyGamer45, after reviewing your issue I want you to try something. Instead of using the op tag use nothing but the normal command and see if that works.

**Comment by CaptainYannick** [comment]
Because you didn't respond this issue will be closed.

**Comment by EarlyGamer45** [comment]
if i remove the op tag it will execute only the first command sorry for late reply
